[package]
name = "rutabaga"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = { version = "0.32.8", features = ["rand-std"] }
clap = { version = "4", features = ["derive"]  }
bitcoinkernel = "0.3"
esplora-client = { version = "0.13.0", features = ["blocking-https"] }

[dev-dependencies]
tempfile = "3"

[[bin]]
name = "cli"
