[package]
name = "rutabaga"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = { version = "0.32", features = ["arbitrary", "rand-std"] }
clap = { version = "4", features = ["derive"]  }
bitcoinkernel = "0.3"
esplora-client = { version = "0.13.0", features = ["blocking-https"] }
bitcoin-coin-selection = { version = "0.9", features = ["rand"] }

[dev-dependencies]
tempfile = "3"
arbtest = "0.3.2"

[[bin]]
name = "cli"
